### ISSUE TITLE
Fix uberjar

### ISSUE THREAD

**Issue by kendru** [kendru/tourbillon#11]
The jar generated with `lein uberjar` fails with the following error:

    Exception in thread "main" java.lang.ExceptionInInitializerError
            at clojure.lang.Namespace.<init>(Namespace.java:34)
            at clojure.lang.Namespace.findOrCreate(Namespace.java:176)
            at clojure.lang.Var.internPrivate(Var.java:151)
            at tourbillon.main.<clinit>(Unknown Source)
    Caused by: java.lang.NoClassDefFoundError: com/stuartsierra/component/Lifecycle, compiling:(user.clj:1:1)
            at clojure.lang.Compiler.load(Compiler.java:7142)
            at clojure.lang.RT.loadResourceScript(RT.java:370)
            at clojure.lang.RT.loadResourceScript(RT.java:357)
            at clojure.lang.RT.maybeLoadResourceScript(RT.java:353)
            at clojure.lang.RT.doInit(RT.java:461)
            at clojure.lang.RT.<clinit>(RT.java:329)
            ... 4 more

Fix so that a standalone jar may be deployed.

**Comment by kendru** [comment]
The workaround is to run `lein do clean, compile, uberjar`. This is aliased as `lein build`.
